spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=devdb
    username: sa
    password: 2p0o2c0Tor
    platform: mssql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  flyway:
    baseline-on-migrate: true
    security:
      user:
        name: admin
        password: admin
  mvc:
    locale: en_US

sms:
  sid: ACd7237b3b93f37a46d212632cde155192
  token: d722955f1b5cec4c6454f6595cea0f30
  number: +16474245036
mail:
  api_key: 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
  address: kuhanp@gmail.com
application:
  url: http://localhost:8081
exception:
  show-stack-trace: false
security:
  disable-authentication: false
