spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: mssql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        format_sql=false:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  flyway:
    baseline-on-migrate: true
    security:
      user:
        name: admin
        password: admin
sms:
  sid: ACd7237b3b93f37a46d212632cde155192
  token: d722955f1b5cec4c6454f6595cea0f30
  number: +16474245036

exception:
  show-stack-trace: false

mail:
  api_key: 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
  address: kuhanp@gmail.com  # this will change once we decide on a companyname and buy the domain

logging:
  level:    root: info
    com.wiserforms.poc: debug

security:
  disable-authentication: false
  